"""
Voice Explanation Module — XAI Finance
Converts SHAP output to plain-English audio using gTTS.
Uses pygame for playback (works on Windows/Mac/Linux).
"""

import numpy as np
import os


def shap_to_speech(shap_vals, features, pred_label, confidence,
                   ticker, save_path="explanation.mp3"):
    """Convert top SHAP features into spoken audio explanation."""
    from gtts import gTTS

    mean_abs = np.abs(shap_vals).mean(axis=0)
    nc       = min(len(mean_abs), len(features))
    top_idx  = np.argsort(mean_abs[:nc])[-3:][::-1]

    top_feats = []
    for i in top_idx:
        fname     = features[i].replace("_", " ")
        direction = "buying" if float(shap_vals[-1][i]) > 0 else "selling"
        top_feats.append(f"{fname}, which is pushing towards {direction}")

    text = (
        f"Analysis for {ticker.replace('.NS','').replace('.BO','')}. "
        f"The AI predicts {pred_label} with {confidence:.0f} percent confidence. "
        f"The top 3 reasons are: "
        f"Number one: {top_feats[0]}. "
        f"Number two: {top_feats[1] if len(top_feats)>1 else 'not available'}. "
        f"Number three: {top_feats[2] if len(top_feats)>2 else 'not available'}. "
        f"This explanation is generated by the XAI Finance dashboard."
    )

    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(save_path)
    return save_path, text
